# Generated by Django 4.1.5 on 2023-01-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formMail', '0002_alter_engineerstudents_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstudents',
            name='med',
            field=models.CharField(max_length=10),
        ),
    ]
