# Generated by Django 4.1.5 on 2023-01-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formMail', '0003_alter_medicalstudents_med'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerstudents',
            name='eng',
            field=models.CharField(max_length=10),
        ),
    ]
